course/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    # path('institute', IndexTemplateView.as_view(), name="index"),
    path('institutes/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/create/', views.InstituteCreate.as_view(), name='institute-create'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),
    path('institute/<int:pk>/delete/', views.InstituteDelete.as_view(), name='institute-delete'),
    path('institute/<int:pk>/update', views.InstituteUpdate.as_view(), name='institute-update'),
]

urlpatterns += [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    path('course/create/', views.CourseCreate.as_view(), name='course-create'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('course/<int:pk>/update', views.CourseUpdate.as_view(), name='course-update'),
]

urlpatterns += [
    path('disciplines/', views.DisciplineListView.as_view(), name='discipline-list'),
    path('discipline/create/', views.DisciplineCreate.as_view(), name='disciplines-create'),
    path('discipline/<int:pk>/', views.DisciplineDetailView.as_view(), name='discipline-detail'),
    path('discipline/<int:pk>/delete/', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:pk>/update', views.DisciplineUpdate.as_view(), name='discipline-update'),
    path('discipline/<int:pk>/import/', views.ImportProfsDiscipline, name='discipline-profs-import'),
    path('discipline/<int:pk>/import2/', views.ImportClassroomsDiscipline, name='discipline-classrooms-import'),
]

urlpatterns += [
    path('classrooms/',               views.ClassroomListView.as_view(), name=''),
    path('classroomsmy/', views.LoanedClassroomByUserListView.as_view(), name='classroom-mylist'),
    path('classroom/create/', views.ClassroomCreate.as_view(), name='classroom-create'),
    path('classroom/<int:pk1>/student/<int:pk2>/delete', views.ClassroomStudentDelete, name='classroom-student-delete'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('classroom/<int:pk>/update', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classroom/<int:pk>/import/', views.ImportStudentsClassroom, name='classroom-students-import'),
    path('classroom/<int:pk>/createNewStudent/', views.ClassroomStudentCreate, name='classroom-student-create'),
]

exam/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/variation/', views.variationsExam, name='exam-variation'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
    path('exam/<int:pk>/moodle/', views.moodle_question, name='exam_moodle'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

course/views.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option)
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
import csv
import io
from datetime import datetime

# Django Imports
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin # Importante para segurança
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect

# App Imports
# Removido import direto de 'account.models' para evitar conflito
from student.models import Student
from .forms import ClassroomCreateForm, ClassroomUpdateForm
from .models import Institute, Course, Discipline, Classroom

# Obtém a classe de Usuário correta
User = get_user_model()


@login_required
@permission_required('exam.change_exam', raise_exception=True)
def ImportClassroomsDiscipline(request, pk):
    discipline = get_object_or_404(Discipline, pk=pk)

    if request.method == 'POST':
        try:
            uploaded_file = request.FILES['myfileClassrooms']
        except KeyError:
            messages.error(request, _('ImportClassroomsDiscipline: choose a CSV following the model'))
            return render(request, 'exam/exam_errors.html', {})

        # 1. Tratamento de Encoding
        try:
            file_data = uploaded_file.read().decode('utf-8')
        except UnicodeDecodeError:
            uploaded_file.seek(0)
            file_data = uploaded_file.read().decode('latin-1')

        # 2. Sniffer (Detecção de separador)
        io_string = io.StringIO(file_data)
        try:
            dialect = csv.Sniffer().sniff(io_string.read(2048), delimiters=[',', ';'])
            io_string.seek(0)
            reader = csv.reader(io_string, dialect)
        except csv.Error:
            io_string.seek(0)
            reader = csv.reader(io_string, delimiter=';')

        # 3. Limpeza: Remove alunos das turmas existentes (comportamento original)
        for c in discipline.classrooms2.all():
            c.students.clear()

        # Links de navegação (Feedback)
        mystr4 = f'/course/discipline/{pk}/update'
        messages.info(request, _('Return to: ') + f'<a href="{mystr4}">link</a>', extra_tags='safe')
        messages.info(request, _('Discipline name') + ' >> ' + discipline.discipline_name, extra_tags='upper')

        # Variáveis auxiliares
        contALL = 0
        contFault = 0
        studentsFault = ''

        # Data para novas turmas
        data_atual = datetime.now()
        ano_quad = f"{data_atual.year}.{(data_atual.month + 3) // 4}"

        # 4. Loop de Importação
        for row in reader:
            if not row: continue

            r = [col.strip() for col in row]

            # Requer pelo menos ID, Nome, Email, Código, Sala, Tipo (6 colunas)
            if len(r) < 6:
                # Se for muito curto, ignora ou loga erro
                if len(r) > 1: print(f"Linha ignorada (incompleta): {r}")
                continue

            try:
                # --- Extração ---
                st_id = r[0]
                st_nome = r[1]
                st_email = r[2]
                class_code = r[3]
                class_room = r[4]
                class_type = r[5]

                # Professor é opcional (coluna 7)
                emailProf = r[6] if len(r) > 6 else None

                # Validação ID
                int(st_id)

                # Tratamento de Nome Grande
                if len(st_nome) > 39:
                    st_nome = st_nome[:39]
                    messages.info(request, f"### BIG ###: {r[1]} ==> {st_nome}")

                # --- PROFESSOR ---
                if emailProf:
                    # Verifica se o professor existe no sistema
                    prof = User.objects.filter(email=emailProf).first()

                    if not prof:
                        # Se não existe, loga o erro (conforme original)
                        # Nota: A lógica original tentava checar institute_url, removi para simplificar,
                        # mas se for vital, avise que recoloco.
                        messages.error(request, _('Teacher not registered: ') + emailProf)
                    else:
                        # Adiciona à disciplina se não estiver
                        if prof not in discipline.discipline_profs.all():
                            discipline.discipline_profs.add(prof)

                # --- ESTUDANTE (Update or Create) ---
                # Resolve o problema da variável 's' indefinida
                s, created = Student.objects.update_or_create(
                    student_ID=st_id,
                    defaults={
                        'student_name': st_nome,
                        'student_email': st_email,
                    }
                )
                contALL += 1

                # --- TURMA (Classroom) ---
                # Busca a turma APENAS dentro desta disciplina
                c, created_c = Classroom.objects.get_or_create(
                    discipline=discipline,
                    classroom_code=class_code,
                    defaults={
                        'classroom_room': class_room,
                        'classroom_type': class_type,
                        'classroom_days': ano_quad,
                    }
                )

                # --- VÍNCULOS ---

                # Adiciona Professor à Turma
                if emailProf and prof:
                    if prof not in c.classroom_profs.all():
                        c.classroom_profs.add(prof)

                # Adiciona Estudante à Turma (Agora 's' e 'c' existem com certeza)
                c.students.add(s)

            except Exception as e:
                contFault += 1
                studentsFault += str(row) + f' ({e})\n'

        # --- RELATÓRIO FINAL ---

        # 1. Turmas
        countClasses = 0
        for c in discipline.classrooms2.all():
            countClasses += 1
            messages.info(request, _('Classroom') + ' >> ' + c.classroom_code, extra_tags='upper')

            # Profs da turma
            for p in c.classroom_profs.all():
                mystr4 = f'PROF: {countClasses}; {p.first_name}; {p.last_name}; {p.email}'
                messages.info(request, mystr4)

            # Alunos da turma
            contS = 0
            for s in c.students.all():
                contS += 1
                mystr4 = f'{contS};    {s.student_ID}; {s.student_name}; {s.student_email}'
                messages.info(request, mystr4)

        # 2. Profs da Disciplina
        messages.info(request, _('Discipline profs'), extra_tags='upper')
        contS = 0
        for p in discipline.discipline_profs.all():
            contS += 1
            mystr4 = f'{contS};    {p.first_name}; {p.last_name}; {p.email}'
            messages.info(request, mystr4)

        # 3. Resumo
        messages.info(request, _('TOTAL'), extra_tags='upper')
        messages.info(request, _('Registered: ') + str(contALL))
        messages.info(request, _('Not registered: ') + str(contFault))
        if studentsFault:
            messages.info(request, str(studentsFault))

    return render(request, 'exam/exam_msg.html', {})

@login_required
@permission_required('exam.change_exam', raise_exception=True)
def ImportProfsDiscipline(request, pk):
    discipline = get_object_or_404(Discipline, pk=pk)

    if request.method == 'POST':
        try:
            uploaded_file = request.FILES['myfileProfs']
        except KeyError:
            messages.error(request, _('ImportProfsDiscipline: choose a CSV following the model!'))
            return render(request, 'exam/exam_errors.html', {})

        # 1. Encoding
        try:
            file_data = uploaded_file.read().decode('utf-8')
        except UnicodeDecodeError:
            uploaded_file.seek(0)
            file_data = uploaded_file.read().decode('latin-1')

        # 2. Sniffer
        io_string = io.StringIO(file_data)
        try:
            dialect = csv.Sniffer().sniff(io_string.read(2048), delimiters=[',', ';'])
            io_string.seek(0)
            reader = csv.reader(io_string, dialect)
        except csv.Error:
            io_string.seek(0)
            reader = csv.reader(io_string, delimiter=';')

        group_prof, created_group = Group.objects.get_or_create(name='professor')

        cont_sucesso = 0
        erros_log = []

        # --- NOVO: Conjunto para guardar IDs dos novos professores adicionados ---
        new_prof_ids = set()

        for row in reader:
            if not row: continue

            r = [col.strip() for col in row]

            if len(r) < 3: continue

            try:
                first_name = r[0]
                last_name = r[1]
                email_prof = r[2].lower()

course/templates/institute/institute_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "Delete Institute" %}</h5>

                <hr>

                {% if user.is_staff %}

                    <p class="card-text">
                        {% trans "Are you sure you want to delete the institute" %}: <code>{{ institute }}</code>?
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <hr/>
                        <div class="text-left">
                            <a href="{% url 'course:institute-list' %}" class="btn btn-outline-danger">
                                {% trans "Cancel" %}
                            </a>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-danger">{% trans "Delete" %}</button>
                        </div>
                    </form>

                {% endif %}

                <hr>
                {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
            </div>
        </div>
    </div>
{% endblock %}

course/templates/institute/institute_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Institute Detail" %}</h5>

                        <hr>

                        <h6 class="card-title"><strong>{% trans "Name" %}: </strong> {{ institute.institute_name }}
                        </h6>
                        <h6><strong>{% trans "Code" %}: </strong>{{ institute.institute_code }}</h6>
                        <h6><strong>{% trans "Logo" %}: </strong>{{ institute.institute_logo }}</h6>
                        <h6><strong>{% trans "URL" %}: </strong>{{ institute.institute_url }}</h6>
                        <h6><strong>{% trans "Exams generated" %}: </strong>{{ institute.institute_exams_generated }}
                        </h6>
                        <h6><strong>{% trans "Exams corrected" %}: </strong>{{ institute.institute_exams_corrected }}
                        </h6>
                        <h6>
                            <strong>{% trans "Questions corrected" %}: </strong>{{ institute.institute_questions_corrected }}
                        </h6>

                        <div style="margin-left:20px;margin-top:20px">
                            <hr>
                            {% csrf_token %}

                            {% if institute.courses2.all %}
                                <div class="card-body" style="background-color:#f3f3f3;">
                                    <h5 class="card-title">{% trans "Course List" %}</h5>
                                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">{% trans "Code" %}</th>
                                            <th scope="col">{% trans "Name" %}</th>
                                            <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for course in institute.courses2.all %}
                                            <tr>
                                                <td>
                                                    <a href="{% url 'course:course-detail'  pk=course.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ course.course_code }}
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'course:course-detail'  pk=course.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ course }}</a>
                                                </td>

                                                <td class="text-right">
                                                    <!-- actions -->
                                                    {% if  user.is_staff %}
                                                        <a href="{% url 'course:course-update'  pk=course.pk %}"
                                                           class="btn btn-outline-primary btn-sm">
                                                            {% trans "Update" %}
                                                        </a>
                                                        <a href="{% url 'course:course-delete'  pk=course.pk %}"
                                                           class="btn btn-outline-danger btn-sm">
                                                            {% trans "Delete" %}
                                                        </a>
                                                    {% endif %}

                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}

                                <div class="text-center mt-5 mb-5 jumbotron">
                                    <h5>{% trans "There is no" %}
                                        <code> {% trans "Course" %} </code> {% trans "registered yet." %}
                                    </h5>
                                </div>

                            {% endif %}

                            {% if  user.is_staff %}
                                <hr/>
                                <div class="text-right">
                                    <a href="{% url 'course:course-create' %}" class="btn btn-primary">
                                        {% trans "Create a New Course" %}
                                    </a>
                                </div>
                            {% endif %}

                            <hr>
                            {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

course/templates/institute/institute_list.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Institute List" %}</h5>

                        {% if institute_list|length > 0 %}

                            <div class="card-body" style="background-color:#f3f3f3;">
                                <table id="example" class="table table-striped table-bordered" style="width:100%">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">{% trans "Code" %}</th>
                                        <th scope="col">{% trans "Name" %}</th>
                                        <th scope="col">{% trans "URL" %}</th>
                                        <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for institute in institute_list %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'course:institute-detail' pk=institute.pk %}"
                                                   class="btn btn-outline-info text-dark btn-sm">
                                                    {{ institute.institute_code }}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'course:institute-detail' pk=institute.pk %}"
                                                   class="btn btn-outline-info text-dark btn-sm">
                                                    {{ institute }}
                                                </a>
                                            </td>
                                            </td>
                                            <td>
                                                <a href="http://{{ institute.institute_url }}"
                                                   class="btn btn-outline-warning text-dark btn-sm">
                                                    {{ institute.institute_url }}
                                                </a>
                                            </td>
                                            <td class="text-right">
                                                {% if  user.is_staff %}

                                                    <a href="{% url 'course:institute-update' pk=institute.pk %}"
                                                       class="btn btn-outline-primary btn-sm">
                                                        {% trans "Update" %}
                                                    </a>

                                                    <a href="{% url 'course:institute-delete' pk=institute.pk %}"
                                                       class="btn btn-outline-danger btn-sm">
                                                        {% trans "Delete" %}
                                                    </a>
                                                {% endif %}

                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>{% trans "There is no" %}
                                    <code> {% trans "Institute" %} </code> {% trans "registered yet." %}</h5>
                            </div>
                        {% endif %}

                        {% if  user.is_staff %}
                            <hr/>
                            <div class="text-right">
                                <a href="{% url 'course:institute-create' %}" class="btn btn-primary">
                                    {% trans "Create a New Institute" %}
                                </a>
                            </div>
                        {% endif %}

                        <hr>
                        {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

course/templates/institute/institute_list.old.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}

    {% if user.is_staff %}

        {% if institute_list %}
            <h1>{% trans "Institute Update" %}</h1>
            <ul>

                {% for institute in institute_list %}
                    <li class="{% if institute.is_overdue %}text-danger{% endif %}">

                        <a href="/course/institute/{{ institute.pk }}/update">{{ institute.institute_code }}
                            - {{ institute.institute_name }}</a>
                    </li>
                {% endfor %}

            </ul>
        {% endif %}

        <form action="../institute/create/" method="">
            {% csrf_token %}
            <input type="submit" action="" value={% trans "Create a new Institute" %}/>
        </form>


    {% else %}

        {% if institute_list %}
            <h1>{% trans "Institute List" %}</h1>

            <ul>

                {% for institute in institute_list %}
                    <li class="{% if institutes.is_overdue %}text-danger{% endif %}">
                        <a href="/course/institute/{{ institute.pk }}">{{ institute.institute_code }}
                            - {{ institute.institute_name }}</a>
                    </li>
                {% endfor %}

            </ul>
        {% endif %}
    {% endif %}

{% endblock %}