course/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    # path('institute', IndexTemplateView.as_view(), name="index"),
    path('institutes/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/create/', views.InstituteCreate.as_view(), name='institute-create'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),
    path('institute/<int:pk>/delete/', views.InstituteDelete.as_view(), name='institute-delete'),
    path('institute/<int:pk>/update', views.InstituteUpdate.as_view(), name='institute-update'),
]

urlpatterns += [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    path('course/create/', views.CourseCreate.as_view(), name='course-create'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('course/<int:pk>/update', views.CourseUpdate.as_view(), name='course-update'),
]

urlpatterns += [
    path('disciplines/', views.DisciplineListView.as_view(), name='discipline-list'),
    path('discipline/create/', views.DisciplineCreate.as_view(), name='disciplines-create'),
    path('discipline/<int:pk>/', views.DisciplineDetailView.as_view(), name='discipline-detail'),
    path('discipline/<int:pk>/delete/', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:pk>/update', views.DisciplineUpdate.as_view(), name='discipline-update'),
    path('discipline/<int:pk>/import/', views.ImportProfsDiscipline, name='discipline-profs-import'),
    path('discipline/<int:pk>/import2/', views.ImportClassroomsDiscipline, name='discipline-classrooms-import'),
]

urlpatterns += [
    path('classrooms/',               views.ClassroomListView.as_view(), name=''),
    path('classroomsmy/', views.LoanedClassroomByUserListView.as_view(), name='classroom-mylist'),
    path('classroom/create/', views.ClassroomCreate.as_view(), name='classroom-create'),
    path('classroom/<int:pk1>/student/<int:pk2>/delete', views.ClassroomStudentDelete, name='classroom-student-delete'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('classroom/<int:pk>/update', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classroom/<int:pk>/import/', views.ImportStudentsClassroom, name='classroom-students-import'),
    path('classroom/<int:pk>/createNewStudent/', views.ClassroomStudentCreate, name='classroom-student-create'),
]

exam/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/variation/', views.variationsExam, name='exam-variation'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
    path('exam/<int:pk>/moodle/', views.moodle_question, name='exam_moodle'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

topic/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path
from course import views as vi
from . import views
from django.urls import reverse

app_name = 'topic'

urlpatterns = [
    path('topics/', views.TopicListView.as_view(), name='topic-list'),
    path('topic/<int:pk>', views.TopicDetailView.as_view(), name='topic-detail'),
]
urlpatterns += [
    path('topic/create/', views.TopicCreate.as_view(), name='topic-create'),
    path('topic/<int:pk>/delete/', views.TopicDelete.as_view(), name='topic-delete'),
    path('topic/<int:pk>/update', views.TopicUpdate.as_view(), name='topic-update'),
    path('topic/<int:pk>/createPDFtopic/', views.see_topic_PDF, name='topic-create-PDF'),
    path('course/<int:pk>/', vi.DisciplineDetailView.as_view(), name='discipline-detail'),
]

urlpatterns += [
    path('questions/', views.QuestionListView.as_view(), name='question-list'),
    path('myquestions/', views.LoanedQuestionByUserListView.as_view(), name='myquestions-list'),
    path('myquestions/import/', views.ImportQuestions, name='myquestions-import'),
    path('myquestions/importImage/', views.ImportQuestionsImage, name='myquestions-import-image'),
    path('myquestions/importJson/', views.ImportQuestionsJson, name='myquestions-import-Json'),
    path('question/<int:pk>/createPDF/', views.see_question_PDF, name='question-create-question-PDF'),
    path('question/<int:pk>/saveJson/', views.save_question_Json, name='question-save-Json'),
]
urlpatterns += [
    path('question/create/', views.QuestionCreate.as_view(), name='question-create'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question-detail'),
    path('question/<int:pk>/update/', views.UpdateQuestion, name='question-update'),
    path('question/<int:pk>/delete/', views.QuestionDelete.as_view(), name='question-delete'),
    path('question/<int:pk>/copy/', views.copy_question, name='copy_question'),
    path('question/<int:pk>/copy/', views.similar_question_ai, name='copy_question'),
    #path('ai-assist/', views.ai_assist, name='ai_assist'),
    # ai_assist: comentado uso em question_update.html - incluir na versão MCTest 5.4
]

course/forms.py
from django import forms

from account.models import User
from .models import Classroom
from .models import Discipline


class ClassroomCreateForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = [
            'discipline',
            'classroom_profs',
            'classroom_code',
            'classroom_room',
            'classroom_days',
            'classroom_type',
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ClassroomCreateForm, self).__init__(*args, **kwargs)

        profs = []
        for d in Discipline.objects.filter(discipline_profs=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)
        for d in Discipline.objects.filter(discipline_coords=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)
        try:
            d1 = Discipline.objects.filter(discipline_profs=user)
            d2 = Discipline.objects.filter(discipline_coords=user)
            self.fields['discipline'].queryset = (d1 | d2).distinct()
            self.fields['classroom_profs'].queryset = User.objects.filter(pk__in=profs).order_by("email")
            self.fields['classroom_profs'].initial = user
        except:
            pass


class ClassroomUpdateForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = [
            'discipline',
            'students',
            'classroom_profs',
            'classroom_code',
            'classroom_room',
            'classroom_days',
            'classroom_type',
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ClassroomUpdateForm, self).__init__(*args, **kwargs)

        profs = []
        for d in Discipline.objects.filter(discipline_profs=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)

        for d in Discipline.objects.filter(discipline_coords=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)
        try:
            d1 = Discipline.objects.filter(discipline_profs=user)
            d2 = Discipline.objects.filter(discipline_coords=user)
            self.fields['discipline'].queryset = (d1 | d2).distinct()
            self.fields['classroom_profs'].queryset = User.objects.filter(pk__in=profs).order_by("email")
        except:
            pass

course/templates/discipline/discipline_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "Delete Discipline" %}</h5>

                <hr>

                {% if user.is_superuser %}

                    <p class="card-text">
                        {% trans "Are you sure you want to delete the discipline" %}: <code>{{ discipline }}</code>?
                    </p>

                    <form method="post">
                        {% csrf_token %}
                        <hr/>
                        <div class="text-left">
                            <a href="{% url 'course:discipline-list' %}" class="btn btn-outline-danger">
                                {% trans "Cancel" %}
                            </a>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-danger">{% trans "Delete" %}</button>
                        </div>
                    </form>

                {% endif %}

                <hr>
                {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
            </div>
        </div>
    </div>
{% endblock %}

course/templates/discipline/discipline_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Discipline Detail" %}</h5>

                        <hr>

                        <!-- header -->
                        <h6><strong>{% trans "Discipline" %}: </strong> {{ discipline.discipline_name }}</h6>
                        <h6><strong>{% trans "Code" %}: </strong>{{ discipline.discipline_code }}</h6>
                        <h6><strong>{% trans "Objective" %}: </strong></h6>
                        {{ discipline.discipline_objective }}

                        <hr>

                        <!-- Profs -->
                        <h6><strong>{% trans "Profs" %}:</strong>
                            {% for p in discipline.discipline_profs.all %}
                                {{ p.username }};
                            {% endfor %}
                        </h6>

                        <!-- Coords -->
                        <h6><strong>{% trans "Coordinator" %}:</strong>
                            {% for c in discipline.discipline_coords.all %}
                                {{ c.username }};
                            {% endfor %}
                        </h6>

                        <!-- Topic List f3f3f3 -->
                        {% if discipline.topics2.all %}
                            <div class="card-body" style="background-color:#f3f3f3;">
                                <h5 class="card-title">{% trans "Topic List" %}</h5>

                                {% if discipline.topics2.all %}

                                    <table id="example0" class="table table-striped table-bordered" style="width:100%">
                                        <thead class="thead-light">
                                        <!-- Topic header -->
                                        <tr>
                                            <th scope="col">{% trans "Topic" %}</th>
                                            <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        {% for topic in discipline.topics2.all %}
                                            <tr>

                                                <!-- topic_text -->
                                                <td>
                                                    <a href="{% url 'topic:topic-detail' pk=topic.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ topic.topic_text }}
                                                    </a>
                                                </td>

                                                <!-- Actions-->
                                                <td class="text-right">

                                                    {% if user.is_superuser or user in discipline.discipline_coords.all %}

                                                        <!-- Update-->
                                                        <a href="{% url 'topic:topic-update'  pk=topic.pk %}"
                                                           class="btn btn-outline-primary btn-sm">
                                                            {% trans "Update" %}
                                                        </a>

                                                        <!-- Delete-->
                                                        <a href="{% url 'topic:topic-delete'  pk=topic.pk %}"
                                                           class="btn btn-outline-danger btn-sm">
                                                            {% trans "Delete" %}
                                                        </a>
                                                    {% endif %}

                                                </td>

                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>


                                {% else %}
                                    <div class="text-center mt-5 mb-5 jumbotron">
                                        <h5>{% trans "There is not " %}
                                            <code> {% trans "Topic" %} </code> {% trans "registered yet." %}
                                        </h5>
                                    </div>
                                {% endif %}

                                <!-- Create a New Topic -->
                                {% if user in discipline.discipline_coords.all %}
                                    <div class="text-right">
                                        <a href="{% url 'topic:topic-create' %}" class="btn btn-primary">
                                            {% trans "Create a New Topic" %}
                                        </a>
                                    </div>
                                {% endif %}

                                {% trans "Only coordinator can create/update/delate topic" %}<br>
                            </div>
                        {% endif %}

                        <p></p>
                        <!-- Discipline List -->
                        {% if discipline.classrooms2.all %}
                            <div class="card-body" style="background-color:#f3f3f3;">
                                <h5 class="card-title">{% trans "Classroom List" %}</h5>

                                <!-- Shows classrooms -->
                                {% if discipline.classrooms2.all %}

                                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                                        <thead class="thead-light">
                                        <!-- Header classrooms -->
                                        <tr>
                                            <th scope="col">{% trans "Code" %}</th>
                                            <th scope="col">{% trans "Period" %}</th>
                                            <th scope="col">{% trans "Profs" %}</th>
                                            <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        {% for classroom in discipline.classrooms2.all %}
                                            <tr>
                                                <!-- classroom_code -->
                                                <td>
                                                    <a href="{% url 'course:classroom-detail' pk=classroom.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ classroom.classroom_code }}
                                                    </a>
                                                </td>
                                                <!-- Period -->
                                                <td>
                                                    {{ classroom.classroom_days }}
                                                </td>
                                                <!-- Profs -->
                                                <td>
                                                    {% for p in classroom.classroom_profs.all %}
                                                        * {{ p.email }}
                                                    {% endfor %}
                                                </td>
                                                <!-- Actions -->
                                                <td class="text-right">
                                                    {% if user.is_superuser or user in classroom.discipline.discipline_coords.all or user in classroom.classroom_profs.all %}

                                                        <!-- Update -->
                                                        <a href="{% url 'course:classroom-update'  pk=classroom.pk %}"
                                                           class="btn btn-outline-primary btn-sm">
                                                            {% trans "Update" %}
                                                        </a>
                                                        <!-- Delete -->
                                                        <a href="{% url 'course:classroom-delete'  pk=classroom.pk %}"
                                                           class="btn btn-outline-danger btn-sm">
                                                            {% trans "Delete" %}
                                                        </a>
                                                    {% endif %}

                                                </td>

                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                {% else %}

                                    <div class="text-center mt-5 mb-5 jumbotron">
                                        <h5>{% trans "There is no" %}
                                            <code> {% trans "Classroom" %} </code> {% trans "registered yet." %}
                                        </h5>
                                    </div>

                                {% endif %}

                                <!-- Create a New Classroom -->
                                {% if user.groups.all.0.name == 'professor' %}
                                    <hr/>
                                    <div class="text-right">
                                        <a href="{% url 'course:classroom-create' %}" class="btn btn-primary">
                                            {% trans "Create a New Classroom" %}
                                        </a>
                                    </div>
                                {% endif %}

                                <!-- End Shows classrooms -->
                                {% trans "Only professor can create/update/delate classroom" %}
                            </div>

                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

course/templates/discipline/discipline_list.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Discipline List" %}</h5>

                        {% if discipline_list %}
                            <div class="card-body" style="background-color:#f3f3f3;">
                                <table id="example" class="table table-striped table-bordered" style="width:100%">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">{% trans "Code" %}</th>
                                        <th scope="col">{% trans "Name" %}</th>
                                        <th scope="col">{% trans "Course" %}</th>
                                        <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for discipline in discipline_list %}
                                        <tr>
                                            <!-- discipline_code -->
                                            <td>
                                                <a href="{% url 'course:discipline-detail'  pk=discipline.pk %}"
                                                   class="btn btn-outline-info text-dark btn-sm">
                                                    {{ discipline.discipline_code }}
                                                </a>
                                            </td>
                                            <!-- discipline_name -->
                                            <td>
                                                <a href="{% url 'course:discipline-detail'  pk=discipline.pk %}"
                                                   class="btn btn-outline-info text-dark btn-sm">
                                                    {{ discipline.discipline_name }}</a>
                                            </td>

                                            <!-- course_code -->
                                            <td>
                                                {% for c in discipline.courses.all %}
                                                    <a href="{% url 'course:course-detail'  pk=c.pk %}"
                                                       class="btn btn-outline-warning text-dark btn-sm">
                                                        {{ c.course_code }}</a>
                                                {% endfor %}
                                            </td>

                                            <!-- Actions -->
                                            <td class="text-right">
                                                {% if user.is_superuser or user in discipline.discipline_coords.all %}

                                                    <a href="{% url 'course:discipline-update'  pk=discipline.pk %}"
                                                       class="btn btn-outline-primary btn-sm">
                                                        {% trans "Update" %}
                                                    </a>
                                                {% endif %}
                                                {% if user.is_superuser %}
                                                    <a href="{% url 'course:discipline-delete'  pk=discipline.pk %}"
                                                       class="btn btn-outline-danger btn-sm">
                                                        {% trans "Delete" %}
                                                    </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>{% trans "There is no" %}
                                    <code> {% trans "Discipline" %} </code> {% trans "registered yet." %}
                                </h5>
                            </div>
                        {% endif %}

                        <!-- Create a New Discipline -->
                        {% if  user.is_staff %}
                            <hr/>
                            <div class="text-right">
                                <a href="{% url 'course:disciplines-create' %}" class="btn btn-primary">
                                    {% trans "Create a New Discipline" %}
                                </a>
                            </div>
                        {% endif %}

                        <hr>
                        {% trans "Only the coordinator can update your discipline" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}