exam/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/variation/', views.variationsExam, name='exam-variation'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
    path('exam/<int:pk>/moodle/', views.moodle_question, name='exam_moodle'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

topic/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path
from course import views as vi
from . import views
from django.urls import reverse

app_name = 'topic'

urlpatterns = [
    path('topics/', views.TopicListView.as_view(), name='topic-list'),
    path('topic/<int:pk>', views.TopicDetailView.as_view(), name='topic-detail'),
]
urlpatterns += [
    path('topic/create/', views.TopicCreate.as_view(), name='topic-create'),
    path('topic/<int:pk>/delete/', views.TopicDelete.as_view(), name='topic-delete'),
    path('topic/<int:pk>/update', views.TopicUpdate.as_view(), name='topic-update'),
    path('topic/<int:pk>/createPDFtopic/', views.see_topic_PDF, name='topic-create-PDF'),
    path('course/<int:pk>/', vi.DisciplineDetailView.as_view(), name='discipline-detail'),
]

urlpatterns += [
    path('questions/', views.QuestionListView.as_view(), name='question-list'),
    path('myquestions/', views.LoanedQuestionByUserListView.as_view(), name='myquestions-list'),
    path('myquestions/import/', views.ImportQuestions, name='myquestions-import'),
    path('myquestions/importImage/', views.ImportQuestionsImage, name='myquestions-import-image'),
    path('myquestions/importJson/', views.ImportQuestionsJson, name='myquestions-import-Json'),
    path('question/<int:pk>/createPDF/', views.see_question_PDF, name='question-create-question-PDF'),
    path('question/<int:pk>/saveJson/', views.save_question_Json, name='question-save-Json'),
]
urlpatterns += [
    path('question/create/', views.QuestionCreate.as_view(), name='question-create'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question-detail'),
    path('question/<int:pk>/update/', views.UpdateQuestion, name='question-update'),
    path('question/<int:pk>/delete/', views.QuestionDelete.as_view(), name='question-delete'),
    path('question/<int:pk>/copy/', views.copy_question, name='copy_question'),
    path('question/<int:pk>/copy/', views.similar_question_ai, name='copy_question'),
    #path('ai-assist/', views.ai_assist, name='ai_assist'),
    # ai_assist: comentado uso em question_update.html - incluir na versão MCTest 5.4
]

topic/models.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
# from django.contrib.auth.models import User
import datetime

from django.db import models
from django.utils.translation import gettext_lazy as _

from account.models import User
from course.models import Course, Discipline, Classroom
from django.shortcuts import get_object_or_404

# Create your models here.
class Topic(models.Model):
    discipline = models.ManyToManyField(Discipline,
                                        related_name='topics2',  # relacionamento reverso
                                        help_text=_("Choose a discipline for this topic."),
                                        verbose_name=_("Disciplines"),
                                        )
    topic_text = models.CharField(max_length=50,
                                  help_text=_("Tip: Include a prefix in the topic, such as discipline code."),
                                  verbose_name=_("Topic"),
                                  )
    topic_description = models.TextField(default='', blank=True, max_length=200,
                                         verbose_name=_("Description"),
                                         )

    def questions(self):
        mylist = [a for a in Question.objects.all() if a.topic.topic_text == self.topic_text]
        mylist = list(dict.fromkeys(mylist)) # remove duplicates
        return mylist

    questions.short_description = 'Questions'

    def display_Questions(self):
        return ', '.join(
            [a.question_short_description for a in Question.objects.all() if a.topic.topic_text == self.topic_text])

    display_Questions.short_description = 'Questions'

    def get_absolute_url(self):
        return "/topic/topics/"
        # return "../topic/%i" % self.id

    class Meta:
        ordering = ["discipline__discipline_code", "topic_text"]

    def __str__(self): # ok
        d = ','.join([d.discipline_code for d in self.discipline.all()])
        t = self.topic_text
        return '[{0}]<{1}>'.format(d, t)


class Question(models.Model):
    topic = models.ForeignKey(Topic,
                              related_name='questions2',  # relacionamento reverso
                              on_delete=models.CASCADE, null=True,
                              verbose_name=_("Topic"),
                              )
    question_group = models.CharField(default='', blank=True, max_length=50,
                                      help_text=_("Only one question per group will be sorted for each exam (student)"),
                                      verbose_name=_("Question Group"),
                                      )
    question_short_description = models.CharField(max_length=50,
                                                  help_text=_("Enter a short description"),
                                                  verbose_name=_("Short Description"),
                                                  )
    question_text = models.TextField(default='', blank=True,
                                     help_text=_(
                                         "Accepts LaTeX description and parameterization using the Python language (see publications)."),
                                     verbose_name=_("Description"),
                                     )

    question_type_choice = (
        ('QM', _('Multiple-Choice Question')),
        ('QT', _('Text Question')),
    )
    question_type = models.CharField(default='', max_length=2,
                                     choices=question_type_choice,
                                     verbose_name=_("Type"),
                                     )
    question_difficulty_choice = (
        ('1', _('Very easy level question')),
        ('2', _('Easy level question')),
        ('3', _('Mid-level question')),
        ('4', _('Difficult level question')),
        ('5', _('Very Difficult level question')),
    )
    question_difficulty = models.CharField(default='', max_length=2,
                                           choices=question_difficulty_choice,
                                           verbose_name=_("Difficulty"),
                                           )
    question_bloom_choice = (
        ('remember', _('remember: recognizing, recalling')),
        ('understand', _('understand: interpreting, exemplifying, classifying, comparing')),
        ('apply', _('apply: executing, implementing')),
        ('analyze', _('analyze: differentiating, organizing, attibuting')),
        ('evaluate', _('evaluate: checking, critiquing')),
        ('create', _('create: generating, planning, producing')),
    )
    question_bloom_taxonomy = models.CharField(default='', max_length=10,
                                               choices=question_bloom_choice,
                                               verbose_name=_("Bloom Taxonomy"),
                                               )


    question_parametric_choice = (
        ('yes', _('Yes')),
        ('no', _('No')),
    )
    question_parametric = models.CharField(
        default='no', max_length=3,
        choices=question_parametric_choice,
        help_text=_("Question with some randomly chosen values"),
        verbose_name=_("Parametric question"))

    question_last_update = models.DateField(default=datetime.date.today, null=True, blank=True,
                                            verbose_name=_("Last Update"),
                                            )
    question_who_created = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                             verbose_name=_("Who Created"),
                                             )

    ''' Novos campos 04/12/2023
primeiro apaga pyc, makemigrations, migrate, detela exames e depois inclui topicos, makemigrations...
find . -path "*/migrations/*.pyc"  -delete
find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
python manage.py makemigrations 
python manage.py makemigrations 
python manage.py migrate
brew services restart mysql

mysql -u root -p DB_MCTest
use DB_MCTest;
show tables;
describe topic_question;

ALTER TABLE topic_question
ADD COLUMN question_correction_count INT DEFAULT 0,
ADD COLUMN question_correct_count INT DEFAULT 0,
ADD COLUMN question_IRT_a_discrimination DOUBLE DEFAULT 0.0,
ADD COLUMN question_IRT_b_ability DOUBLE DEFAULT 0.0,
ADD COLUMN question_IRT_c_guessing DOUBLE DEFAULT 0.0;


UPDATE topic_question SET
question_correction_count = IFNULL(question_correction_count, 0),
question_correct_count = IFNULL(question_correct_count, 0),
question_IRT_a_discrimination = IFNULL(question_IRT_a_discrimination, 0.0),
question_IRT_b_ability = IFNULL(question_IRT_b_ability, 0.0),
question_IRT_c_guessing = IFNULL(question_IRT_c_guessing, 0.0);

    '''
    question_correction_count = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name=_("Correction Count"))
    question_correct_count = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name=_("Correct Count"))
    question_IRT_a_discrimination = models.FloatField(default=0.0, null=True, blank=True, verbose_name=_("Discrimination"))
    question_IRT_b_ability = models.FloatField(default=-5.0, null=True, blank=True, verbose_name=_("Ability"))
    question_IRT_c_guessing = models.FloatField(default=0.0, null=True, blank=True, verbose_name=_("Guessing"))

    def display_Topic(self):
        return self.topic.topic_text

    display_Topic.short_description = 'Topic'

    def answers(self):
        question_inst = get_object_or_404(Question, pk=self.id)
        return [a for a in question_inst.answers2.all()]
        #return [a for a in Answer.objects.all() if a.question.id == self.id]

    answers.short_description = 'Answers'

    def display_Answers(self):
        question_inst = get_object_or_404(Question, pk=self.id)
        return ', '.join([a.answer_text for a in question_inst.answers2.all()])
        #return ', '.join([a.answer_text for a in Answer.objects.all() if a.question.id == self.id])

    display_Answers.short_description = 'Answers'

    class Meta:
        ordering = ["topic__discipline__discipline_code", "topic__topic_text", "question_type", "question_difficulty",
                    "question_group", "question_short_description"]
        permissions = (("can_mark_update", "Set question as validated"),)

    def get_absolute_url(self):
        return "../question/%i" % self.id

    def __str__(self): # ok
        # u  = ';'.join([d. for d in Discipline.objects.all() if (self.user
        # d = ';'.join([d.discipline_code for d in Discipline.objects.all() if (d in self.topic.discipline.all())])
        # t = ';'.join([t.topic_text for t in Topic.objects.all() if (t == self.topic)])
        d = 'oi_d_lento'
        t = self.topic.topic_text
        df = "dif " + self.question_difficulty
        g = "gro " + self.question_group
        p = "par " + self.question_parametric
        tp = "typ " + self.question_type
        id = "#" + str(self.id).zfill(4)

topic/templates/topic/topic_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "Delete Topic" %}</h5>

                <hr>

                {% if user.groups.all.0.name == 'professor' %}

                    <!-- message -->
                    <script> var count = 0; </script>
                    {% for d in topic.discipline.all %}
                        {% if user in d.discipline_coords.all %}
                            <script>
                                if (count == 0) {
                                    document.write("<p>{% trans 'Are you sure you want to delete the topic' %}: <code>{{ topic }}</code>?</p>");
                                }
                                count++;
                            </script>
                        {% endif %}
                    {% endfor %}

                    <!-- actions -->
                    <form method="post">
                        {% csrf_token %}
                        <hr/>
                        <div class="text-left">
                            <a href="{% url 'topic:topic-list' %}" class="btn btn-outline-danger">
                                {% trans "Cancel" %}
                            </a>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-danger">{% trans "Delete" %}</button>
                        </div>
                    </form>

                    <!-- message -->
                    <script>
                        document.write("<hr>");
                        if (count > 1) {
                            document.write("<br>{% trans 'Note that you will delete a topic that belongs to more than one discipline!' %}")
                        }
                    </script>

                {% endif %}

                <hr>
                <h3><code>{% trans 'All questions connected this topic will be removed from the database!' %}</code>
                </h3>
            </div>
        </div>
    </div>
{% endblock %}

topic/templates/topic/topic_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Topic Detail" %}</h5>

                        <hr>

                        <script>
                            String.prototype.padFunction = function (padStr, len) {
                                var str = this;
                                while (str.length < len)
                                    str = padStr + str;
                                return str;
                            }
                        </script>

                        <h1><strong>{% trans "Topic" %}: </strong> {{ topic.topic_text }}</h1>
                        <h4><strong>{% trans "Description" %}: </strong>{{ topic.topic_description }}</h4>

                        <hr>

                        {% for d in topic.discipline.all|slice:":1" %}
                            {% if user.is_superuser or user in d.discipline_coords.all or user in d.discipline_profs.all %}

                                <!-- Create-PDF -->
                                <table style="width:100%">
                                    <tr>
                                        <th>
                                            <form class="input-group mb-3" target="_blank"
                                                  action="{% url 'topic:topic-create-PDF' pk=topic.id %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-primary" type="submit" action=""
                                                       value={% trans "Create-PDF" %}>
                                            </form>
                                        </th>
                                        <th style="text-align:left">
                                            <h6>{% trans "View all questions in this topic in PDF format, sorted by similarity" %}</h6>
                                        </th>
                                    </tr>
                                </table>

                                <hr>

                                {% if topic.questions %}

                                    <div class="card-body" style="background-color:#f3f3f3;">
                                        <h5 class="card-title">{% trans "Questions List" %}</h5>
                                        <table id="example" class="table table-striped table-bordered"
                                               style="width:100%">
                                            <thead class="thead-light">

                                            <!-- header -->
                                            <tr>
                                                <th scope="col">{% trans "Topic" %}</th>
                                                <th scope="col">{% trans "Type" %}</th>
                                                <th scope="col">{% trans "Group" %}</th>
                                                <th scope="col">{% trans "Dif." %}</th>
                                                <th scope="col">{% trans "Par." %}</th>
                                                <th scope="col">{% trans "ID" %}</th>
                                                <th scope="col">{% trans "Short Description" %}</th>
                                                <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                            </tr>
                                            </thead>

                                            <!-- list topic.questions -->
                                            <tbody>
                                            {% for question in topic.questions %}
                                                <tr>

                                                    <!-- topic -->
                                                    <td>
                                                        <a href="{% url 'topic:topic-detail' pk=question.topic_id %}"
                                                           class="btn btn-outline-warning text-dark btn-sm">
                                                            {{ question.topic }}
                                                        </a>
                                                    </td>

                                                    <!-- question_type -->
                                                    <td>
                                                        <a href="{% url 'topic:question-detail' pk=question.pk %}"
                                                           class="btn btn-outline-light text-dark btn-sm">
                                                            {{ question.question_type }}
                                                            {% if question.question_type == 'QM' %}
                                                                {{ question.answers2.all|length }}
                                                            {% endif %}
                                                        </a>
                                                    </td>
                                                    <!-- question_group -->
                                                    <td>
                                                        <a href="{% url 'topic:question-detail' pk=question.pk %}"
                                                           class="btn btn-outline-light text-dark btn-sm">
                                                            {{ question.question_group }}
                                                        </a>
                                                    </td>
                                                    <!-- question_difficulty -->
                                                    <td>
                                                        <a href="{% url 'topic:question-detail' pk=question.pk %}"
                                                           class="btn btn-outline-light text-dark btn-sm">
                                                            {{ question.question_difficulty }}
                                                        </a>
                                                    </td>
                                                    <!-- question_parametric -->
                                                    <td>
                                                        <a href="{% url 'topic:question-detail' pk=question.pk %}"
                                                           class="btn btn-outline-light text-dark btn-sm">
                                                            {{ question.question_parametric }}
                                                        </a>
                                                    </td>
                                                    <!-- pk -->
                                                    <td>
                                                        <a href="{% url 'topic:question-detail' pk=question.pk %}"
                                                           class="btn btn-outline-light text-dark btn-sm">
                                                            {{ question.pk }}
                                                        </a>
                                                    </td>
                                                    <!-- question_short_description -->
                                                    <td>
                                                        <a href="{% url 'topic:question-detail' pk=question.pk %}"
                                                           class="btn btn-outline-info text-dark btn-sm">
                                                            {{ question.question_short_description }}
                                                        </a>
                                                    </td>

                                                    <!-- actions -->
                                                    <td class="text-right">
                                                        {% for d in question.topic.discipline.all|slice:":1" %}
                                                            {% if user.is_superuser or user in d.discipline_coords.all  or user in d.discipline_profs.all %}
                                                                <!-- Update -->
                                                                <a href="{% url 'topic:question-update'  pk=question.pk %}"
                                                                   target="_blank"
                                                                   class="btn btn-outline-primary btn-sm">
                                                                    {% trans "Update" %}
                                                                </a>
                                                                <!-- Delete -->
                                                                <a href="{% url 'topic:question-delete'  pk=question.pk %}"
                                                                   target="_blank"
                                                                   class="btn btn-outline-danger btn-sm">
                                                                    {% trans "Delete" %}
                                                                </a>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </td>

                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>

                                {% else %}

                                    <!-- If there is no question -->
                                    <div class="text-center mt-5 mb-5 jumbotron">
                                        <h5>{% trans "There is no" %}
                                            <code> {% trans "Question" %} </code> {% trans "registered yet." %}
                                        </h5>
                                    </div>

                                {% endif %}

                                <!-- Create a New Question    -->
                                <script> var count = 0; </script>
                                <hr/>
                                <div class="text-right">
                                    {% for q in question_list %}
                                        {% for d in q.topic.discipline.all %}
                                            {% if user.is_superuser or user in d.discipline_coords.all or user in d.discipline_profs.all %}
                                                <script>
                                                    if (count == 0) {
                                                        document.write("<a href=\"{% url 'topic:question-create' %}\" class=\"btn btn-primary\">");
                                                        document.write("{%  trans 'Create a New Question' %}</a>")
                                                    }
                                                    count++;
                                                </script>
                                            {% endif %}
                                        {% endfor %}
                                    {% endfor %}
                                </div>
                            {% else %}
                                <h4>{% trans "No permission to access this content!" %}</h4>
                            {% endif %}

                        {% endfor %}

                        <hr>
                        {% trans "Note: For each exam, only one question is taken from each group" %}<br>
                        {% trans "Only the teacher registered in the course can see more details" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}