course/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    # path('institute', IndexTemplateView.as_view(), name="index"),
    path('institutes/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/create/', views.InstituteCreate.as_view(), name='institute-create'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),
    path('institute/<int:pk>/delete/', views.InstituteDelete.as_view(), name='institute-delete'),
    path('institute/<int:pk>/update', views.InstituteUpdate.as_view(), name='institute-update'),
]

urlpatterns += [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    path('course/create/', views.CourseCreate.as_view(), name='course-create'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('course/<int:pk>/update', views.CourseUpdate.as_view(), name='course-update'),
]

urlpatterns += [
    path('disciplines/', views.DisciplineListView.as_view(), name='discipline-list'),
    path('discipline/create/', views.DisciplineCreate.as_view(), name='disciplines-create'),
    path('discipline/<int:pk>/', views.DisciplineDetailView.as_view(), name='discipline-detail'),
    path('discipline/<int:pk>/delete/', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:pk>/update', views.DisciplineUpdate.as_view(), name='discipline-update'),
    path('discipline/<int:pk>/import/', views.ImportProfsDiscipline, name='discipline-profs-import'),
    path('discipline/<int:pk>/import2/', views.ImportClassroomsDiscipline, name='discipline-classrooms-import'),
]

urlpatterns += [
    path('classrooms/',               views.ClassroomListView.as_view(), name=''),
    path('classroomsmy/', views.LoanedClassroomByUserListView.as_view(), name='classroom-mylist'),
    path('classroom/create/', views.ClassroomCreate.as_view(), name='classroom-create'),
    path('classroom/<int:pk1>/student/<int:pk2>/delete', views.ClassroomStudentDelete, name='classroom-student-delete'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('classroom/<int:pk>/update', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classroom/<int:pk>/import/', views.ImportStudentsClassroom, name='classroom-students-import'),
    path('classroom/<int:pk>/createNewStudent/', views.ClassroomStudentCreate, name='classroom-student-create'),
]

exam/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/variation/', views.variationsExam, name='exam-variation'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
    path('exam/<int:pk>/moodle/', views.moodle_question, name='exam_moodle'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

student/urls.py
'''
=====================================================================
Copyright (C) 2018-2026 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.4.

Languages: Python, Django and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    # path('student', IndexTemplateView.as_view(), name="index"),
    path('students/', views.StudentListView.as_view(), name='student-list'),
    path('classroom/<int:pk>/student/create/', views.StudentCreate.as_view(), name='student-create'),
    path('student/<int:pk>/', views.StudentDetailView.as_view(), name='student-detail'),
    path('student/<int:pk>/delete/', views.StudentDelete.as_view(), name='student-delete'),
    path('student/<int:pk>/update', views.StudentUpdate.as_view(), name='student-update'),
]

course/forms.py
from django import forms

from account.models import User
from .models import Classroom
from .models import Discipline


class ClassroomCreateForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = [
            'discipline',
            'classroom_profs',
            'classroom_code',
            'classroom_room',
            'classroom_days',
            'classroom_type',
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ClassroomCreateForm, self).__init__(*args, **kwargs)

        profs = []
        for d in Discipline.objects.filter(discipline_profs=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)
        for d in Discipline.objects.filter(discipline_coords=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)
        try:
            d1 = Discipline.objects.filter(discipline_profs=user)
            d2 = Discipline.objects.filter(discipline_coords=user)
            self.fields['discipline'].queryset = (d1 | d2).distinct()
            self.fields['classroom_profs'].queryset = User.objects.filter(pk__in=profs).order_by("email")
            self.fields['classroom_profs'].initial = user
        except:
            pass


class ClassroomUpdateForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = [
            'discipline',
            'students',
            'classroom_profs',
            'classroom_code',
            'classroom_room',
            'classroom_days',
            'classroom_type',
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ClassroomUpdateForm, self).__init__(*args, **kwargs)

        profs = []
        for d in Discipline.objects.filter(discipline_profs=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)

        for d in Discipline.objects.filter(discipline_coords=user):
            for p in d.discipline_profs.all():
                profs.append(p.pk)
            for p in d.discipline_coords.all():
                profs.append(p.pk)
        try:
            d1 = Discipline.objects.filter(discipline_profs=user)
            d2 = Discipline.objects.filter(discipline_coords=user)
            self.fields['discipline'].queryset = (d1 | d2).distinct()
            self.fields['classroom_profs'].queryset = User.objects.filter(pk__in=profs).order_by("email")
        except:
            pass

course/templates/classroom/classroom_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Classroom Detail" %}</h5>

                        <hr>

                        <h5><strong>{% trans "Classroom" %}: </strong> {{ classroom.classroom_code }}</h5>
                        <h6><strong>{% trans "Type" %}: </strong>{{ classroom.classroom_type }}</h6>
                        <h6><strong>{% trans "Period" %}: </strong>{{ classroom.classroom_days }}</h6>
                        <h6><strong>{% trans "Profs" %}: </strong>
                            {% for prof in classroom.classroom_profs.all %}
                                * {{ prof }}
                            {% endfor %}
                        </h6>

                        {% if user.is_superuser or user in classroom.discipline.discipline_coords.all or user in classroom.classroom_profs.all %}

                            <div style="margin-left:20px;margin-top:20px">
                                <hr>

                                {% csrf_token %}

                                <!-- Shows students -->
                                {% if classroom.students.all %}

                                    <div class="card-body" style="background-color:#f3f3f3;">
                                        <h5 class="card-title">{% trans "Students List" %}</h5>
                                        <table id="example" class="table table-striped table-bordered"
                                               style="width:100%">
                                            <thead class="thead-light">

                                            <!-- Topic header -->
                                            <tr>
                                                <th scope="col">{% trans "ID" %}</th>
                                                <th scope="col">{% trans "Student" %}</th>
                                                <th scope="col">{% trans "Email" %}</th>
                                                <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for student in classroom.students.all %}
                                                <tr>
                                                    <!-- student_ID -->
                                                    <td>
                                                        <a href="{% url 'student:student-detail' pk=student.pk %}"
                                                           class="btn btn-outline-info text-dark btn-sm">
                                                            {{ student.student_ID }}
                                                        </a>
                                                    </td>
                                                    <!-- student_name -->
                                                    <td>
                                                        <a href="{% url 'student:student-detail' pk=student.pk %}"
                                                           class="btn btn-outline-info text-dark btn-sm">
                                                            {{ student.student_name }}
                                                        </a>
                                                    </td>
                                                    <!-- student_email -->
                                                    <td>
                                                        <a href="{% url 'student:student-detail' pk=student.pk %}"
                                                           class="btn btn-outline-info text-dark btn-sm">
                                                            {{ student.student_email }}
                                                        </a>
                                                    </td>

                                                    <!-- Actions -->
                                                    <td class="text-right">
                                                        {% if user.is_superuser or user in classroom.discipline.discipline_coords.all or user in classroom.discipline.discipline_profs.all %}
                                                            <!-- Update -->
                                                            <a href="{% url 'student:student-update'  pk=student.pk %}"
                                                               class="btn btn-outline-primary btn-sm">
                                                                {% trans "Update" %}
                                                            </a>
                                                            <!-- Delete -->
                                                            <a href="{% url 'course:classroom-student-delete' pk1=classroom.pk pk2=student.pk %}"
                                                               class="btn btn-outline-danger btn-sm">
                                                                {% trans "Delete" %}
                                                            </a>
                                                        {% endif %}
                                                    </td>

                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    {% if classroom.disciples2.all %}
                                        <h1>{% trans "Classrooms" %}</h1>
                                        <ul>
                                            {% for c in classroom.disciples2.all %}
                                                <li class="{% if c.is_overdue %}text-danger{% endif %}">
                                                    <a href="{% url 'course:classroom-detail'  pk=c.pk %}">
                                                        {{ c }}
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}

                                {% else %}

                                    <div class="text-center mt-5 mb-5 jumbotron">
                                        <h5>{% trans "There are no" %}
                                            <code> {% trans "Student" %} </code> {% trans "registered yet." %}
                                        </h5>
                                    </div>

                                {% endif %}
                                <!-- End Shows students -->

                            </div>
                        {% else %}
                            <h4>{% trans "No permission to access this content!" %}</h4>
                        {% endif %}

                        {% if user in classroom.discipline.discipline_coords.all or user.groups.all.0.name == 'professor' and user in classroom.classroom_profs.all %}
                            <hr/>
                            <script>
                                function validateForm() {
                                    var x = document.forms["myForm"]["fname"].value;
                                    if (x == "" || x == null) {
                                        alert("Name must be filled out");
                                        return false;
                                    }
                                }
                            </script>
                            <div class="text-right">
                                <!-- Create a new Student -->
                                <form action="{% url 'course:classroom-student-create' pk=classroom.pk %}" class="input-group mb-3" method="POST" target="_blank"
                                      name="myForm" onsubmit="return validateForm()">
                                    {% csrf_token %}
                                    <table class="table">
                                        <tr>
                                            <td style="width: 150px; height: 40px; font-size: 15px;" align="left"
                                                bgcolor="#e6f2ff">
                                                <label for="nameID">{% trans "ID" %}</label>
                                                <input style="width: 100px; height: 40px; font-size: 15px;"
                                                       type="number" id="student_ID" name="student_ID"
                                                       required="required"/>
                                            </td>
                                            <td style="width: 450px; height: 40px; font-size: 15px;" align="left"
                                                bgcolor="#e6f2ff">
                                                <label for="name">{% trans "Name" %}</label>
                                                <input style="width: 300px; height: 40px; font-size: 15px;" type="text"
                                                       id="student_name" name="student_name" required="required"/>
                                            </td>
                                            <td style="width: 400px; height: 40px; font-size: 15px;" align="left"
                                                bgcolor="#e6f2ff">
                                                <label for="nameEmail">{% trans "Email" %}</label>
                                                <input style="width: 250px; height: 40px; font-size: 15px;" type="email"
                                                       id="student_email" name="student_email" required="required"/>
                                            </td>
                                            <td style="width: 250px; height: 40px; font-size: 15px;" align="right"
                                                bgcolor="#e6f2ff">
                                                <input action="" class="btn btn-primary" type="submit"
                                                       value="{% trans "Create a new Student" %}">
                                            </td>
                                        </tr>
                                    </table>
                                </form>
                            </div>
                            <div class="text-right">
                                <a href="{% url 'course:classroom-update' pk=classroom.pk %}"
                                   class="btn btn-primary">
                                    {% trans "Update Classroom by CSV" %}
                                </a>
                            </div>

                        {% endif %}

                        <hr>
                        {% trans "Attention, a student may be many classrooms" %}<br>
                        {% trans "One student will be removed from the class" %}<br>
                        {% trans "Import students by CSV file in Update Classroom" %}<br>
                        {% trans "Only teacher registered in Classroom or coordinator" %}<br>
                        {% trans "Contact your discipline coordinator" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

course/templates/classroom/classroom_list.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Classrooms List" %}</h5>

                        {% if user.groups.all.0.name == 'professor' %}

                            {% if classroom_list %}
                                <div class="card-body" style="background-color:#f3f3f3;">
                                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">{% trans "Classroom Code" %}</th>
                                            <th scope="col">{% trans "Discipline" %}</th>
                                            <th scope="col">{% trans "Period" %}</th>
                                            <th scope="col">{% trans "Profs" %}</th>
                                            <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        {% for classroom in classroom_list %}
                                            <tr>
                                                <td>
                                                    <a href="{% url 'course:classroom-detail' pk=classroom.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ classroom.classroom_code }}
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'course:discipline-detail' pk=classroom.discipline.pk %}"
                                                       class="btn btn-outline-warning text-dark btn-sm">
                                                        {{ classroom.discipline }}
                                                    </a>
                                                </td>
                                                <!-- Period -->
                                                <td>
                                                    {{ classroom.classroom_days }}
                                                </td>
                                                <!-- Profs -->
                                                <td>

                                                        {% for p in classroom.classroom_profs.all %}
                                                                  * {{ p.email }}
                                                        {% endfor %}

                                                </td>

                                                <!-- Actions -->
                                                <td class="text-right">
                                                    {% if user.is_superuser or user in classroom.discipline.discipline_coords.all or user in classroom.classroom_profs.all %}
                                                        <a href="{% url 'course:classroom-update'  pk=classroom.pk %}"
                                                           class="btn btn-outline-primary btn-sm">
                                                            {% trans "Update" %}
                                                        </a>
                                                        <a href="{% url 'course:classroom-delete'  pk=classroom.pk %}"
                                                           class="btn btn-outline-danger btn-sm">
                                                            {% trans "Delete" %}
                                                        </a>
                                                    {% endif %}
                                                </td>

                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                                <div class="text-center mt-5 mb-5 jumbotron">
                                    <h5>{% trans "There is no" %}
                                        <code> {% trans "Classroom" %} </code> {% trans "registered yet." %}
                                    </h5>
                                </div>
                            {% endif %}

                            <hr/>
                            <!-- Create a New Classroom -->
                            <div class="text-right">
                                <a href="{% url 'course:classroom-create' %}" class="btn btn-primary">
                                    {% trans "Create a New Classroom" %}
                                </a>
                            </div>

                            <hr/>

                        {% endif %}

                        <hr>
                        {% trans "Only teacher registered in a discipline" %}<br>
                        {% trans "Contact your discipline coordinator" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

course/templates/classroom/simple_upload.html
{% extends "base_generic.html" %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <button type="submit">Upload</button>
    </form>
{% endblock %}

course/templates/classroom/simple_upload.old.html
{% extends "base_generic.html" %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <button type="submit">Upload</button>
    </form>
{% endblock %}